apps/blog/urls.py
from django.conf.urls import include, url

from .views import BlogIndexView, BlogListView, BlogDetailView

app_name = 'blog'

urlpatterns = [
	url(r'^$', BlogIndexView.as_view(), name='blog_index'),
	url(r'^posts/$', BlogListView.as_view(), name='blog_list'),
	url(r'^(?P<slug>[-\w]+)/?$', BlogDetailView.as_view(), name ='blog_detail'),
]

apps/flatpage/urls.py
from django.conf.urls import include, url

from .views import IndexFlatpageView, AboutFlatpageView, ContactFlatpageView

app_name = 'flatpage'

urlpatterns =[
	url(r'^$', IndexFlatpageView.as_view(), name='index'),
	url(r'^about-us/?$', AboutFlatpageView.as_view(), name='about_index'),
	url(r'^contact-us/?$', ContactFlatpageView.as_view(), name='contact_index')
]

apps/shop/urls.py
from django.conf.urls import include, url

from .views import ShopIndexView

app_name='shop'

urlpatterns = [
	url(r'^$', ShopIndexView.as_view(), name='shop_index'),
]

apps/upload/urls.py
from django.conf.urls import include, url

from .views import VideoIndexView, VideoListView, VideoDetailView

app_name = 'upload'

urlpatterns = [
	url(r'^$', VideoIndexView.as_view(), name='video_index'),
    url(r'^(?P<slug>[-\w]+)/?$', VideoDetailView.as_view(), name='video_detail'),
]

project/urls.py
from django.contrib import admin
from django.conf.urls import include, url
from django.urls import include, path

from django.conf import settings
from django.conf.urls.static import static

from apps.search.views import VideoSearchView

admin.site.site_title = 'Sam Dale Academy Administration'
admin.site.site_header = 'Sam Dale Academy LLC'

urlpatterns = [
    url(r'^admin/', admin.site.urls, name='admin'),
]

urlpatterns += [
    url(r'', include('apps.flatpage.urls', namespace='flatpage')),
    url(r'^videos/', include('apps.upload.urls', namespace='upload')),
    url(r'^search/?$', VideoSearchView.as_view(), name='video_search_view'), #override haystack view, custom url directs to custom view
    url(r'^our-blog/', include('apps.blog.urls', namespace='blog')),
    url(r'^shop/', include('apps.shop.urls', namespace='shop')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT) + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

templates/global/partials/footer.html
{% load staticfiles %}

{% block extrastyles %}
<link rel="stylesheet" href="{% static 'global/css/ds.css' %}">
<style>
  .fc-white-dark{
    color:#626262;
  }
  .bg-gray{
    color:#dbe0dd;
  }
</style>
{% endblock %}

<!-- Footer -->
<footer id="footer" class="bottom-0 px-0">
  <!-- Copyright -->
  <div class="bottom-0 bg-white pt-2">  
    <div class="footer-ic col-6-fr">
      <!-- Facebook -->
      <a class="ic" href="https://www.facebook.com/SamDaleAcademyLLC/" target="_blank"><i class="fab fa-facebook fa-lg fc-black"></i></a>
      <!-- Twitter -->
      <a class="ic" href="https://twitter.com/Samdaleacademy_" target="_blank"><i class="fab fa-twitter fa-lg fc-black mx-4"></i></a>
      <!--Instagram-->
      <a class="ic" href="https://www.instagram.com/samdaleacademy_sda/" target="_blank"><i class="fab fa-instagram fa-lg fc-black"></i></a>
    </div>
    <p class="footer-copyright col-6-fl txt-12 fc-black">© 2018 Copyright : Sam Dale Academy LLC</p>
  </div> 
</footer>

    

templates/global/partials/nav2_drawer.html
{% load staticfiles %}
{% block extrastyles %}
<style>
/* mobile first */
/* nav side drawer */
.wrapper {
	display: flex;
	width: 50%;
}
/* drawer markup */
#drawer {
	position: fixed;
	top: 0;
	left: 0;
	width: 270px;
	height: 100vh;
	z-index: 9999;
	transition: all .2s;
	margin-left: -270px;
	min-width: 270px;
	max-width: 270px;
}
#drawer.active {
	margin-left: 0;
}

/* navbar markup */
ul{
	list-style-type: none !important;
	margin: 0 !important;
	padding: 0 !important;
}
a{
	text-decoration: none !important;
}
ul.menu-items-mobile{
	width: 100%;
}
ul.menu-items-mobile li a{
	font-family: 'Montserrat', sans-serif;
	font-weight:400;
	font-size: 12px;
	text-transform: uppercase;
	color: white;
}

ul.menu-items-mobile li{
	padding: 15px 15px;
}
ul.menu-items-mobile li:hover{
	background-color: #121212;
}
ul.menu-items-mobile ul.li-content li a{
	padding: 0;
}
ul.menu-items-mobile li.li-target{
	font-family: 'Montserrat', sans-serif;
	font-weight:400;
	font-size: 12px;
	text-transform: uppercase;
	color: lightgray;
	background-color: #121212;
}

</style>
{% endblock %}
<nav id="drawer" class="bg-darker shadow-lg">
	<nav class="navbar h-65 bg-darker border-bottom border-dark">
		<button id="drawer-times" class="border-0 bg-darker p-0">
			<div class="times">
				<div class="tl">
					<div class="tr"></div>
				</div>
			</div>
		</button>
	</nav>
	<ul class="menu-items-mobile">
		<div class="li-group">
			<li class="li-target">Twenty Three Hours</li>
			<ul class="li-content">
				<li class="sublink"><a href="{% url 'upload:video_index' %}">Videos</a></li>
				<li class="sublink"><a href="{% url 'blog:blog_index' %}">Our Blog</a></li>
			</ul>
		</div>
		<li><a href="{% url 'flatpage:about_index' %}">About Us</a></li>
		<li><a href="">Sessions & Camps</a></li>
		<li><a href="">SDA Gear</a></li>
	</ul>
</nav>
	
<!--scripts-->
{% block extrascripts %}
<script>
	(function(){
		function drawerListeners(){
			var target = document.getElementById("drawer");
			var overlay = document.getElementsByClassName("overlay");
			document.getElementById("toggler-bars").addEventListener("click", function(){
				$(target).addClass("active");
				$(overlay).addClass("active");
			})
			document.getElementById("drawer-times").addEventListener("click", function(){
				$(target).removeClass("active");
				$(overlay).removeClass("active");
			})
		}
		document.addEventListener("DOMContentLoaded", drawerListeners, false);
	})();
</script>
{% endblock %}

templates/global/partials/nav2_primary.html
{% load static %}

{% block extrastyles %}
<link rel="stylesheet" type="text/css" href="{% static 'global/css/ds.css' %}">
<link rel="stylesheet" type="text/css" href="{% static 'global/css/ds-nav.css' %}">
<style>
	nav.nav-bar{
		display: flex;
		flex-direction: row;
		align-items: center;
		width: 100vw;
		padding: 0 15px;
	}
	.nav-brand{
		position: absolute;
		margin: 0 0 0 20px;
	}
	nav ul{
		display: inline-block;
	}
	button#toggler-bars > div:nth-child(2){
		margin: 5px 0;
	}
	.icon-bar{
		background-color: white !important;
		width: 18px !important;
		height: 2px !important;
	}
	@media(max-width:768px){
		nav.nav-bar.primary{
			height: 65px;
		}
		.nav-brand{
			position: absolute;
			left: 50%;
			transform: translateX(-50%);
		}
		.nav-brand > img {
			height: 40px;
		}
		ul.nav-items.primary,
		ul.nav-items.secondary{
			display: none;
		}
		#toggler-bars{
			position: absolute;
			left: 25px;
		}
	}
	@media(min-width: 768px){
		nav.nav-bar.primary{
			height: 70px;
		}
		.nav-brand > img {
			height: 44px;
		}
		.icon-bar{
			display: none;
		}
		/* primary links */
		ul.nav-items li,
		ul.nav-items a{
			color: white;
			font-size: 13px;
			font-weight: 400;
		}
		ul.nav-items > li{
			display: inline;
		}
		ul.nav-items.primary{
			position: relative;
			left: 50%;
			transform: translateX(-50%);
		}
		ul.nav-items.primary > li{
			padding: 21px 8px;
		}
		/* secondary links */
		ul.nav-items.secondary{
			position: absolute;
			right: 15px;
		}
		ul.nav-items.secondary > li:nth-child(1){
			padding: 0 10px;
		}
		ul.nav-items.secondary > li:nth-child(2){
			padding: 10px 20px;
			border: 1px solid gray;
			border-radius: 5px;
		}
		ul.nav-items.secondary > li:nth-child(2) a{
			text-transform: uppercase;
		}
		ul.nav-items > li.li-target{
			position: relative;
		}
		/* link dropdown content, sublinks */
		ul.nav-items > li.li-target ul.li-content{
			visibility: hidden;
			position: absolute;
			left: 0;
			top: 60px;
			background-color: #f8f9fa;
			min-width: 200px;
			box-shadow: 0px 4px 8px 0px rgba(0,0,0,0.2);
			z-index: 1;
			opacity:0;
			transition:500ms ease;
			border-top:2px solid red ;
		}
		ul.nav-items .li-content > li{
			padding: 10px 30px;
		}
		ul.nav-items .li-content > li a{
			font-size: 14px;
			font-weight: 500;
			color: #343a40;
		}
		ul.nav-items .li-content > li:first-child{
			margin: 15px 0 0;
		}
		ul.nav-items .li-content > li:last-child{
			margin: 0 0 15px;
		}
		ul.nav-items ul.li-content li:hover{
			background-color: white;
		}
		ul.nav-items > li.li-target:hover ul.li-content{
			visibility: visible;
			opacity:1;
		}
	}
</style>
{% endblock %}

<div class="wrapper">
	<div id="toggler">
		<nav class="nav-bar primary bg-darker">
			<button id="toggler-bars" class="border-0 bg-transparent p-0">
				<div class="icon-bar"></div>
				<div class="icon-bar"></div>
				<div class="icon-bar"></div>
			</button>
			<a class="nav-brand" href="{% url 'flatpage:index' %}"><img src="{% static 'global/img/brand/sda_site_logo_header_sample1.png' %}" alt="Brand Logo"></a>
			<ul class="nav-items primary">
				<li class="li-target">Twenty Three Hours<span class="fas fa-caret-down pl-1"></span>
					<ul class="li-content">
						<li><a href="{% url 'upload:video_index' %}">Videos</a></li>
						<li><a href="{% url 'blog:blog_index' %}">Our Blog</a></li>
					</ul>
				</li>
				<li><a href="{% url 'flatpage:about_index' %}">About Us</a></li>
				<li class="li-target">Services<span class="fas fa-caret-down pl-1"></span>
					<ul class="li-content">
						<li><a href="">Sessions & Camps</a></li>
						<li><a href="">Highlight Tapes</a></li>
					</ul>
				</li>
				<li><a href="{% url 'shop:shop_index' %}">SDA Gear</a></li>
			</ul>
			<ul class="nav-items secondary" id="account">
				<li><a href="">Log In</a></li>
				<li><a href="">Sign Up</a></li>
			</ul>
		</nav>
	</div>
	{% include './nav2_drawer.html' %}
    <!-- Dark Overlay element -->
    <div class="overlay"></div>
</div>

<script>
</script>