apps/blog/urls.py
from django.conf.urls import include, url

from .views import BlogIndexView, BlogListView, BlogDetailView

app_name = 'blog'

urlpatterns = [
	url(r'^$', BlogIndexView.as_view(), name='blog_index'),
	url(r'^posts/$', BlogListView.as_view(), name='blog_list'),
	url(r'^(?P<slug>[-\w]+)/?$', BlogDetailView.as_view(), name ='blog_detail'),
]

project/urls.py
from django.contrib import admin
from django.conf.urls import include, url
from django.urls import include, path

from django.conf import settings
from django.conf.urls.static import static

from apps.search.views import VideoSearchView

admin.site.site_title = 'Sam Dale Academy Administration'
admin.site.site_header = 'Sam Dale Academy LLC'

urlpatterns = [
    url(r'^admin/', admin.site.urls, name='admin'),
]

urlpatterns += [
    url(r'', include('apps.flatpage.urls', namespace='flatpage')),
    url(r'^videos/', include('apps.upload.urls', namespace='upload')),
    url(r'^search/?$', VideoSearchView.as_view(), name='video_search_view'), #override haystack view, custom url directs to custom view
    url(r'^our-blog/', include('apps.blog.urls', namespace='blog')),
    url(r'^shop/', include('apps.shop.urls', namespace='shop')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT) + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

apps/blog/models.py
from django.db import models
from django.contrib.auth.models import User
from django.utils import timezone


# Create your models here.
class Post(models.Model):
    author = models.ForeignKey(User, on_delete=models.CASCADE)
    title = models.CharField(max_length=200, null = True)
    description = models.CharField(max_length=200, null=True)
    image = models.ImageField(upload_to = 'blog/img/', null = True)
    text = models.TextField(null=True)
    slug = models.SlugField(unique=True)
    published_date = models.DateTimeField(default=timezone.now)

    def publish(self):
        self.published_date = timezone.now()
        self.save()

    def __str__(self):
        return self.title

    

apps/blog/views.py
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponse
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.views.generic import TemplateView, ListView, DetailView
from .models import Post
# Create your views here.

class BlogIndexView(TemplateView):
	context_object_name="post"
	template_name="blog/blog_index.html"
	model=Post
	context = {}
	def get(self, request):
		try:
			self.context['primary'] = self.model.objects.all().order_by('-published_date')[0]
			self.context['grid'] = self.model.objects.all().order_by('-published_date')[1:]

			return render(request, self.template_name, {self.context_object_name:self.context})

		except IndexError:

			return HttpResponse("Sorry, This page is under construction...") 

class BlogListView(ListView):
	context_object_name = 'post'
	template_name="blog/blog_list.html"
	model = Post

	def get(self,request):
	    post_list = self.model.objects.all().order_by('-published_date')
	    paginator = Paginator(post_list, 3) # Show 2 posts per page
	    page = request.GET.get('page')
	    try:
	        posts = paginator.page(page)
	    except PageNotAnInteger:
	        # If page is not an integer, deliver first page.
	        posts = paginator.page(1)
	    except EmptyPage:
	        # If page is out of range (e.g. 9999), deliver last page of results.
	        posts = paginator.page(paginator.num_pages)

	    return render(request, self.template_name, {self.context_object_name: posts})


class BlogDetailView(DetailView):
	context_object_name= 'post'
	template_name='blog/blog_detail.html'
	
	def get(self, request, slug):
		queryset = get_object_or_404(Post, slug=slug)

		return render(request, self.template_name, {self.context_object_name:queryset})

apps/blog/templates/blog/blog_detail.html
{% extends 'global/layout.html' %}
{% load staticfiles %}

{% block title %}Our Blog{% endblock %}

{% block header %}
<header class="container-fluid nav-mb-sm ht-md bg-light">
	<div class="container p-wrapper px-5 py-5 wpc-80">
		<p class="heading1">{{ post.title }}</p>
		{% if post.published_date %}
		<p class="txt-14">published: {{ post.published_date }}</p>
	    {% endif %}
	</div>
</header>
{% endblock %}

{% block content %}
	<div class="container p-wrapper nav-overlap ht-md bg-white px-5 py-4 wpc-80">
		<p class="txt-16">{{post.text}}</p>
	</div>
{% endblock %}

{# override footer, no footer this page #}
{% block footer %}{% endblock %}

apps/blog/templates/blog/blog_index.html
{% extends 'global/layout.html' %}
{% load staticfiles %}

{% block extrastyles %}
<link href="https://fonts.googleapis.com/css?family=Barlow+Semi+Condensed:600,700" rel="stylesheet">
<style>
    header{
        background-image: linear-gradient(rgba(0, 0, 0, 0.4), rgba(0, 0, 0, 0.5)), url('{% static 'blog/img/blog_bg.jpg' %}');
        background-attachment: fixed;
        background-repeat: no-repeat;
        background-position: center;
        background-size: 100% 100%;
        height: 100vh;
        margin: -60px 0 0 0;
        display: flex;
        flex-direction: column;
        justify-content: center;
        align-items: center;
    }
    header > section > blockquote{
        text-align: center;
        font-size: 25px;
        font-family: 'Barlow Semi Condensed', sans-serif;
        font-weight: 600;
        line-height: 40px;
        color: white;
        width: 80vw;
    }
    header > section > form {
        margin: 40px 0;
    }
    @media(min-width:768px){
        header > section > blockquote{
            text-align: center;
            font-size: 50px;
            font-family: 'Barlow Semi Condensed', sans-serif;
            font-weight: 600;
            line-height: 70px;
            color: white;
            width: 80vw;
        }
    }
    
</style>
{% endblock %}

{% block title %}Our Blog{% endblock %}

{% block header %}
<header>
    <section>
        <blockquote>“ What you do in your 1-2 hours of training doesn't make you a pro, it makes you a player, but the 22-23 hours outside of the training is what makes you a professional. ”</blockquote>
    </section>
</header>
{% endblock %}
{% block content %}
<figure id="grid-3x" class="container-fluid">
	{% for p in post.grid %}
        <a href="{% url 'blog:blog_detail' slug=p.slug %}">
            <div class="thumbnail-wrapper">
                {% if p.image %}
	                <img src="{{ MEDIA_URL }}{{p.image}}" alt="thumbnail">
	            {% endif %}
                <div class="thumb-info">
                    <p class="thumb-text-primary pt-1 mb-1">{{ p.title }}</p>
                    <p class="thumb-text-secondary">{{p.description|truncatewords:9|linebreaksbr}}</p>
                </div>
            </div>
        </a>
	{% endfor %}
</figure>
<!--pagination-->
<div class="pagination d-flex justify-content-center">
   <a href="{% url 'blog:blog_list' %}">See More.</a>
</div>
{% endblock %}

apps/blog/templates/blog/blog_list.html
{% extends 'global/layout.html' %}
{% load staticfiles %}

{% block title %}Our Blog | Posts{% endblock %}

{% block content %}
<figure id="grid-3x" class="container-fluid nav-mb-sm">
	{% for p in post %}
        <a href="{% url 'blog:blog_detail' slug=p.slug %}">
            <div class="thumbnail-wrapper">
                {% if p.image %}
	                <img src="{{ MEDIA_URL }}{{p.image}}" alt="thumbnail">
	            {% endif %}
                <div class="thumb-info">
                    <p class="thumb-text-primary pt-1 mb-1">{{ p.title }}</p>
                    <p class="thumb-text-secondary">{{p.description|truncatewords:9|linebreaksbr}}</p>
                </div>
            </div>
        </a>
	{% endfor %}
</figure>
<!--pagination-->
<div class="pagination d-flex justify-content-center">
    <span class="step-links">
    	<a href="{% url 'blog:blog_index' %}">&laquo; first</a>
        {% if post.has_previous %}
            <a href="{% url 'blog:blog_list'%}?page={{ post.previous_page_number }}">previous</a>
        {% endif %}

        <span class="current">
            Page {{ post.number }} of {{ post.paginator.num_pages }}.
        </span>

        {% if post.has_next %}
            <a href="?page={{ post.next_page_number }}">next</a>
            <a href="?page={{ post.paginator.num_pages }}">last &raquo;</a>
        {% endif %}
    </span>
</div>
{% endblock %}

apps/blog/templates/blog/untitled.html
{% block header %}
	<header class="container-fluid nav-mb ht-md bg-darker d-flex flex-column justify-content-center align-items-center">
		<p class="heading1 fc-white">Our Blog</p>
		<blockquote class="text-center wpc-60 pt-3">
			<p class="txt-14-light fc-white">"What you do in your 1-2 hours of training doesn’t make you a pro, it makes you a player, but the 22-23 hours outside of the training is what makes you a professional."</p>
			<footer class="blockquote-footer txt-12-light fc-white-darker"><cite title="Source Title">SDA Academy</cite></footer>
		</blockquote>
	</header>
{% endblock %} 