apps/upload/urls.py
from django.conf.urls import include, url

from .views import VideoIndexView, VideoListView, VideoDetailView

app_name = 'upload'

urlpatterns = [
	url(r'^$', VideoIndexView.as_view(), name='video_index'),
    url(r'^(?P<slug>[-\w]+)/?$', VideoDetailView.as_view(), name='video_detail'),
]

project/urls.py
from django.contrib import admin
from django.conf.urls import include, url
from django.urls import include, path

from django.conf import settings
from django.conf.urls.static import static

from apps.search.views import VideoSearchView

admin.site.site_title = 'Sam Dale Academy Administration'
admin.site.site_header = 'Sam Dale Academy LLC'

urlpatterns = [
    url(r'^admin/', admin.site.urls, name='admin'),
]

urlpatterns += [
    url(r'', include('apps.flatpage.urls', namespace='flatpage')),
    url(r'^videos/', include('apps.upload.urls', namespace='upload')),
    url(r'^search/?$', VideoSearchView.as_view(), name='video_search_view'), #override haystack view, custom url directs to custom view
    url(r'^our-blog/', include('apps.blog.urls', namespace='blog')),
    url(r'^shop/', include('apps.shop.urls', namespace='shop')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT) + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

apps/upload/models.py
from django.db import models
from django.contrib.auth.models import User
from django.utils import timezone
from videokit.models import VideoField, VideoSpecField
from django.core.validators import MinLengthValidator

# Create your models here.
class Video(models.Model):
	author = models.ForeignKey(User, on_delete=models.CASCADE)
	title = models.CharField(max_length=100, validators=[MinLengthValidator(25)], null=True, default="Title Lorem ipsum dolor sit amet, consectetur adipisicing elit.")
	description = models.CharField(max_length=200, null=True, default="Description Lorem ipsum dolor sit amet, consectetur adipisicing elit.")
	video = VideoField(upload_to = 'upload/video/', null = True,
    	mimetype_field = 'video_mimetype',
    	duration_field = 'video_duration',
    	thumbnail_field = 'video_thumbnail')
	video_thumbnail = models.ImageField(upload_to = 'upload/img/', blank=True, null=True)
	text = models.TextField(null=True, default="Text Lorem ipsum dolor sit amet, consectetur adipisicing elit. Sed cupiditate porro reprehenderit, quibusdam modi, ex iusto similique dolore autem magni quae molestias doloremque hic maxime maiores laudantium dolores, assumenda illum.")
	slug = models.SlugField(unique=True)
	published_date = models.DateTimeField(default=timezone.now)
	video_mimetype = models.CharField(max_length = 32, blank = True, null=True)
	video_duration = models.IntegerField(blank = True, null = True)
	video_mp4 = VideoSpecField(source = 'video', format = 'mp4')
	video_ogg = VideoSpecField(source = 'video', format = 'ogg')
	video_webm = VideoSpecField(source = 'video', format = 'webm')

	def publish(self):
		self.published_date = timezone.now()
		self.save()

	def __str__(self):
		return self.title

apps/upload/views.py
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponse
from django.views.generic import TemplateView, ListView, DetailView
from .models import Video

# Create your views here.
class VideoIndexView(TemplateView):
	context_object_name = "media"
	template_name = "upload/video_index.html"
	model = Video
	context = {}
	def get(self, request):
		try:
			self.context['primary'] = self.model.objects.all().order_by('-published_date')[0]
			self.context['secondary'] = self.model.objects.all().order_by('-published_date')[1:7]
			self.context['grid'] = self.model.objects.all().order_by('-published_date')[7:]

			return render(request, self.template_name, {self.context_object_name:self.context})

		except IndexError:

			return HttpResponse("Sorry, This page is under construction...") 

class VideoListView(ListView):
	context_object_name = "media"
	template_name = "upload/video_list.html"

	def get(self, request):
		queryset = Video.objects.all().order_by('-published_date')

		return render(request, self.template_name, {self.context_object_name:queryset})

class VideoDetailView(TemplateView):
	context_object_name = "media"
	template_name ="upload/video_detail.html"
	model = Video
	context={}

	def get(self,request, slug):
		self.context['primary'] = get_object_or_404(self.model, slug=slug)
		self.context['secondary'] = self.model.objects.all().order_by('-published_date')[1:7]
		self.context['grid'] = self.model.objects.all().order_by('-published_date')[7:]

		return render(request, self.template_name, {self.context_object_name: self.context})

apps/upload/templates/upload/video_detail.html
{% extends 'upload/video_index.html' %}

apps/upload/templates/upload/video_index.html
{% extends 'global/layout.html' %}
{% load staticfiles %}


{% block extrastyles %}
<link href="https://vjs.zencdn.net/7.2.3/video-js.css" rel="stylesheet">
{% endblock %}

{% block title %}Videos{% endblock %}

{% block header %}
<figure id="video-player" class="container-fluid" style="margin-top:150px;">
	<div id="playlist-video-main">
		<video controls>
			<source src="{{MEDIA_URL}}{{media.primary.video}}" type="video/mp4">
			<source src="" type="video/webm">
			<p class="vjs-no-js">
				To view this video please enable JavaScript, and consider upgrading to a web browser that
				<a href="https://videojs.com/html5-video-support/" target="_blank">supports HTML5 video</a>
			</p>
		</video>
		<div id="playlist-video-main-info">
			<p id="video-main-title" class="video-main-text-primary pt-4 mb-3">{{media.primary.title}}</p>
			<p id="video-main-description" class="video-main-text-secondary">{{media.primary.description}}</p>
		</div>
	</div>
	{% if media.secondary %}
	<figcaption id="playlist-video-secondary">
		<div class="heading-banner-sm d-flex align-items-center"><p class="heading2 my-0">Next up.</p></div>
		<div class="wrapper-scroll">
		{% for m in media.secondary %}
			<a href="{{MEDIA_URL}}{{m.video}}">
				<div class="thumbnail-wrapper">
					<img src="{{MEDIA_URL}}{{m.video_thumbnail}}" alt="playlist video thumbnail"> 
					<div class="playlist-video-secondary-info">
						<p href="{{m.title}}" class="thumb-text-primary pt-1">{{m.title|truncatewords:5|linebreaksbr}}</p>
						<p href="{{m.description}}"></p>
					</div>
				</div>
			</a>
		{% endfor %}
		</div>
	</figcaption>
	{% endif %}
</figure>
{% endblock %}

{% block content %}
{% if media.grid %}
<figure id="grid-4x" class="container-fluid">
	<div class="heading-banner-lg d-flex align-items-center"><p class="heading2 mb-0">More Drills.</p></div>
	{% for m in media.grid %}
        <a href="{% url 'upload:video_detail' slug=m.slug %}">
            <div class="thumbnail-wrapper">
                <img src="{{ MEDIA_URL }}{{m.video_thumbnail}}" alt="playlist video thumbnail">
                <div class="thumb-info">
                    <p class="thumb-text-primary pt-1 mb-1">{{m.title|truncatewords:5|linebreaksbr}}</p>
                </div>
            </div>
        </a>
    {% endfor %}
</figure> 
{% endif %}
{% endblock %}


{# override footer, no footer for this page #}
{% block footer %}{% endblock %}

<!--scripts-->
{% block extrascripts %}
<script src="https://vjs.zencdn.net/7.2.3/video.js"></script>
<script type="text/javascript" src="{% static 'global/js/ds.video.bundle.js' %}"></script>
{% endblock %}